// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC6CTzD7NP3UxT_saqdw__spNRc-IG9hk',
    appId: '1:1014685930063:web:98948b4205b9ea7ed2503a',
    messagingSenderId: '1014685930063',
    projectId: 'sport-cee71',
    authDomain: 'sport-cee71.firebaseapp.com',
    storageBucket: 'sport-cee71.appspot.com',
    measurementId: 'G-3B5JV62C6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxuag9D38zFc6UGCEEKdKeRFh1qxjwaXs',
    appId: '1:1014685930063:android:906011a9a606adbdd2503a',
    messagingSenderId: '1014685930063',
    projectId: 'sport-cee71',
    storageBucket: 'sport-cee71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKE_vNTmaZF5oO9cqyFe6Ks9qnbQEX774',
    appId: '1:1014685930063:ios:1531d7760ce0bb32d2503a',
    messagingSenderId: '1014685930063',
    projectId: 'sport-cee71',
    storageBucket: 'sport-cee71.appspot.com',
    iosClientId: '1014685930063-68dgsilmdqucl2taoqomilins346gqd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKE_vNTmaZF5oO9cqyFe6Ks9qnbQEX774',
    appId: '1:1014685930063:ios:1531d7760ce0bb32d2503a',
    messagingSenderId: '1014685930063',
    projectId: 'sport-cee71',
    storageBucket: 'sport-cee71.appspot.com',
    iosClientId: '1014685930063-68dgsilmdqucl2taoqomilins346gqd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSport',
  );
}
